# Generated by Django 4.2.5 on 2023-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prenotazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('data', models.DateField(null=True)),
                ('primadonazione', models.CharField(max_length=255)),
            ],
        ),
    ]
