# Generated by Django 4.2.5 on 2024-01-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazioni',
            old_name='primadonazione',
            new_name='analisieffettuate',
        ),
    ]
