version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn jupiter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/jupiter/web/staticfiles
    expose:
      - 8000
    env_file:
      - web.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/jupiter/web/staticfiles
      - certs:/home/jupiter/ssl
    ports:
      - 1642:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  certs:
