# Generated by Django 4.2.5 on 2023-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donatori',
            fields=[
                ('tessera', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('grupposang', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('datadinascita', models.DateField(null=True)),
                ('luogodinascita', models.CharField(max_length=255)),
                ('codicefiscale', models.CharField(max_length=16)),
                ('indirizzo', models.CharField(max_length=255)),
                ('comune', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
