# Generated by Django 4.2.5 on 2023-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatori',
            name='fenotipo',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donatori',
            name='kell',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
