# Generated by Django 4.2.5 on 2023-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0005_alter_donatori_fototessera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatori',
            name='fototessera',
            field=models.ImageField(default='default.jpg', upload_to='fototessere/'),
        ),
    ]
