# Generated by Django 4.2.5 on 2023-11-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0007_donatori_qrverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatori',
            name='fenotipo',
        ),
        migrations.RemoveField(
            model_name='donatori',
            name='kell',
        ),
    ]
