# Generated by Django 4.2.5 on 2023-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0008_remove_donatori_fenotipo_remove_donatori_kell'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatori',
            name='privacy_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donatori',
            name='privacy_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donatori',
            name='privacy_c',
            field=models.BooleanField(default=False),
        ),
    ]
