# Generated by Django 4.2.5 on 2023-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0009_donatori_privacy_a_donatori_privacy_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatori',
            name='autorizzazione',
            field=models.ImageField(null=True, upload_to='autorizzazioni/'),
        ),
        migrations.AddField(
            model_name='donatori',
            name='modReferti',
            field=models.CharField(default='', max_length=255),
        ),
    ]
