# Generated by Django 4.2.5 on 2023-12-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0010_donatori_autorizzazione_donatori_modreferti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatori',
            name='autorizzazione',
            field=models.ImageField(blank=True, null=True, upload_to='autorizzazioni/'),
        ),
    ]
