# Generated by Django 4.2.5 on 2023-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idoneita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nominativo', models.CharField(max_length=255)),
                ('dataprelievo', models.DateField(null=True)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
    ]
