# Generated by Django 4.2.5 on 2023-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoneita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='idoneo',
            field=models.CharField(default='No', max_length=255),
            preserve_default=False,
        ),
    ]
