# Generated by Django 4.2.5 on 2023-10-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoneita', '0002_idoneita_idoneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
