# Generated by Django 4.2.5 on 2023-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoneita', '0003_idoneita_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idoneita',
            name='email',
        ),
        migrations.AlterField(
            model_name='idoneita',
            name='idoneo',
            field=models.CharField(default='In attesa', max_length=255),
        ),
    ]
