# Generated by Django 4.2.5 on 2023-10-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donatori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('tipo', models.CharField(max_length=255)),
                ('quantitativo', models.CharField(max_length=255)),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donatori.donatori')),
            ],
        ),
    ]
