# Generated by Django 4.2.5 on 2023-11-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donazioni',
            name='quantitativo',
        ),
    ]
