# Generated by Django 4.2.5 on 2023-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0002_remove_donazioni_quantitativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donazioni',
            name='referto',
            field=models.FileField(blank=True, null=True, upload_to='referti/'),
        ),
    ]
